
[functions.flutterwave-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/flutterwave-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/flutterwave-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/flutterwave-webhook/*.html" ]

[functions.create-subaccount]
enabled = true
verify_jwt = true
import_map = "./functions/create-subaccount/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-subaccount/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-subaccount/*.html" ]
